import os

from docx import Document

from ReportTestUtils import TEN_YEARS_RANGE, TEST_CITY_NAME, TEST_RIVER_NAME
from dataset_provider import DatasetProvider
from dataset_provider.DataFrameForObliczenieObjetosciOrazSumObjetosci import createDataFrameForObliczenieObjestosciOrazSumObjetosciTable
from operat_report_tests import ReportTestUtils
from table_generator.ObjetosciISumyObjetosciTableGenerator import appendObliczenieObjetosciISumObjetosciTableToDocument

os.chdir("../")

# loaded settings from project_settings.json file
include_first_row_for_higher_in_frequency_table = True
common_range_of_states_for_multiannual = True

# test settings
parameter_name = 'Q'

document = Document()
dataset_for_years = DatasetProvider.provideDataForDailyFlowsAndStatesInYears(TEN_YEARS_RANGE, TEST_CITY_NAME, TEST_RIVER_NAME)

df_for_objetosci_i_sumy_objetosci_table = createDataFrameForObliczenieObjestosciOrazSumObjetosciTable(dataset_for_years, save_to_file=False)

appendObliczenieObjetosciISumObjetosciTableToDocument(document, df_for_objetosci_i_sumy_objetosci_table)

ReportTestUtils.saveTestDocumentFileAndPrintFileName(document)
